workflows:
  android-release:
    name: DSZ Save Chat Android Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
      java: 1.17
    scripts:
      - name: Force Java 17 and Set up Environment
        script: |
          LATEST_JAVA_17=$(ls -d /usr/lib/jvm/java-17-openjdk-* | head -n 1)
          if [ -d "$LATEST_JAVA_17" ]; then
            export JAVA_HOME="$LATEST_JAVA_17"
            export PATH="$JAVA_HOME/bin:$PATH"
          fi
          java -version
          mkdir -p android
          echo "flutter.sdk=$FLUTTER_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get packages
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/app/outputs/flutter-apk/*.apk
      - "**/*.apk"
    publishing:
      email:
        recipients:
          - rwasifdsz.2006@gmail.com
        notify:
          success: true
          failure: true
