package com.example.core.localization

data class LocalizedContent(
    val appName: String,
    val brandSlogan: String,
    val authorTagline: String,
    val splashSubtitle: String,
    val splashLoading: String,
    val tabChats: String,
    val tabMedia: String,
    val tabSettings: String,
    val subTabAll: String,
    val subTabMessenger: String,
    val subTabBusiness: String,
    val searchChatsPlaceholder: String,
    val filterAll: String,
    val filterDeleted: String,
    val filterWhatsApp: String,
    val filterTelegram: String,
    val filterDirect: String,
    val emptyChatsTitle: String,
    val emptyChatsSubtitle: String,
    val mediaEmptyTitle: String,
    val mediaEmptySubtitle: String,
    val adBannerTitle: String,
    val deletedMessageBadge: String,
    val secureOfflineBadge: String,
    val addTestChatButton: String,
    val exportChatsButton: String,
    val themeSectionTitle: String,
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val languageSectionTitle: String,
    val youtubeSectionTitle: String,
    val youtubeChannelName: String,
    val youtubeChannelHandle: String,
    val youtubeChannelDesc: String,
    val youtubeSubscribeBtn: String,
    val youtubeWatchBtn: String,
    val youtubeSubscribersCount: String,
    val youtubeVideosCount: String,
    val aboutDeveloperTitle: String,
    val developerName: String,
    val developerRole: String,
    val privacyTitle: String,
    val privacyDesc: String,
    val replaySplashButton: String,
    val offlineStatusTitle: String,
    val offlineStatusDesc: String,
    // Settings Items
    val settingLanguageTitle: String,
    val settingLanguageSubtitle: String,
    val settingThemeTitle: String,
    val settingThemeSubtitle: String,
    val settingModeTitle: String,
    val settingModeSubtitle: String,
    val settingPrimaryLockTitle: String,
    val settingPrimaryLockSubtitle: String,
    val settingVaultLockTitle: String,
    val settingVaultLockSubtitle: String,
    val settingAutoDownloadTitle: String,
    val settingAutoDownloadSubtitle: String,
    val settingStorageTitle: String,
    val settingStorageSubtitle: String,
    val settingBatteryTitle: String,
    val settingBatterySubtitle: String,
    val settingUpdatesTitle: String,
    val settingUpdatesSubtitle: String,
    val updatesCurrentVersionTitle: String,
    val updatesCheckNowBtn: String,
    val updatesDownloadBtn: String,
    val updatesUpToDateDesc: String,
    val updatesChangelogTitle: String,
    val footerSlogan: String,
    val settingPermissionsTitle: String,
    val settingPermissionsSubtitle: String,
    val permissionNotificationTitle: String,
    val permissionNotificationDesc: String,
    val permissionStorageTitle: String,
    val permissionStorageDesc: String,
    val permissionGrantedBadge: String,
    val permissionMissingBadge: String,
    val permissionContinueBtn: String,
)

object AppStrings {
    private val english = LocalizedContent(
        appName = "DSZ Save Chat",
        brandSlogan = "Building with Purpose. Creating for People.",
        authorTagline = "by M Wasif DSZ",
        splashSubtitle = "Offline Chat Saver & Archiver",
        splashLoading = "Initializing secure offline engine...",
        tabChats = "Chats",
        tabMedia = "Media",
        tabSettings = "Settings",
        subTabAll = "All",
        subTabMessenger = "Messenger",
        subTabBusiness = "Business",
        searchChatsPlaceholder = "Search saved chats & messages...",
        filterAll = "All Messages",
        filterDeleted = "Deleted Alerts",
        filterWhatsApp = "WhatsApp",
        filterTelegram = "Telegram",
        filterDirect = "Direct",
        emptyChatsTitle = "No Saved Chats Yet",
        emptyChatsSubtitle = "Incoming notifications and chat backups will automatically appear here offline.",
        mediaEmptyTitle = "No Deleted Media Saved",
        mediaEmptySubtitle = "Deleted photos, audio notes, and videos captured from notifications will be preserved here.",
        adBannerTitle = "Ad • DSZ Network",
        deletedMessageBadge = "DELETED RECOVERED",
        secureOfflineBadge = "100% OFFLINE",
        addTestChatButton = "Simulate New Incoming Chat",
        exportChatsButton = "Export Offline Backup",
        themeSectionTitle = "Appearance & Theme",
        themeSystem = "System Default",
        themeLight = "Warm Cream Light",
        themeDark = "Charcoal Gold Dark (Default)",
        languageSectionTitle = "Language Selection",
        youtubeSectionTitle = "Creator Official Channel",
        youtubeChannelName = "واصف ریفری کول (Wasif RefriCool)",
        youtubeChannelHandle = "@WasifRefriCool",
        youtubeChannelDesc = "Official HVAC & refrigeration engineering tutorials, tech innovations, and appliance guides by M Wasif DSZ.",
        youtubeSubscribeBtn = "Subscribe Channel",
        youtubeWatchBtn = "Watch Tutorials",
        youtubeSubscribersCount = "15K+ Subscribers",
        youtubeVideosCount = "180+ Videos",
        aboutDeveloperTitle = "About Developer & Brand",
        developerName = "M Wasif DSZ",
        developerRole = "Software Architect & Creator",
        privacyTitle = "Zero-Cloud Guarantee",
        privacyDesc = "All chat logs remain strictly in local storage on your device. No telemetry or server syncing.",
        replaySplashButton = "Preview Splash Screen",
        offlineStatusTitle = "100% Offline & Private",
        offlineStatusDesc = "No server connections, no external telemetry. Designed for absolute privacy.",
        settingLanguageTitle = "App Language",
        settingLanguageSubtitle = "Switch app language between English and Urdu instantly.",
        settingThemeTitle = "Theme Appearance",
        settingThemeSubtitle = "Default Dark Theme with toggle to Warm Cream Light Theme.",
        settingModeTitle = "Online & Offline Mode",
        settingModeSubtitle = "Default OFF (Online only). Turn ON to enable hybrid 24/7 background offline saving.",
        settingPrimaryLockTitle = "Primary App Lock",
        settingPrimaryLockSubtitle = "Set, change, or remove 4-digit PIN for your real chat history.",
        settingVaultLockTitle = "Vault / Secondary Lock",
        settingVaultLockSubtitle = "Set, change, or remove secret decoy PIN that reveals a clean empty screen.",
        settingAutoDownloadTitle = "Auto-Download Media",
        settingAutoDownloadSubtitle = "Automatically save deleted photos and videos or download manually.",
        settingStorageTitle = "Storage & Media Cleaner",
        settingStorageSubtitle = "View app storage usage and clear cache or old media files safely.",
        settingBatteryTitle = "Battery Optimization Guide",
        settingBatterySubtitle = "Ensure the app runs smoothly in the background 24/7 without delay.",
        settingUpdatesTitle = "Check for Updates",
        settingUpdatesSubtitle = "Check remote version and download latest APK securely in browser.",
        updatesCurrentVersionTitle = "Current Version: v2.4.0 (Stable Release)",
        updatesCheckNowBtn = "Check for Updates",
        updatesDownloadBtn = "Update Now (Download APK)",
        updatesUpToDateDesc = "You are running the official build of DSZ Save Chat by M Wasif DSZ. All local storage is safely preserved during updates.",
        updatesChangelogTitle = "Recent Updates & Features",
        footerSlogan = "Building with Purpose. Creating for People.",
        settingPermissionsTitle = "Notification & App Permissions",
        settingPermissionsSubtitle = "Manage WhatsApp live interception & local storage permissions.",
        permissionNotificationTitle = "Notification Listener Access",
        permissionNotificationDesc = "Required for instant WhatsApp & WhatsApp Business live capture.",
        permissionStorageTitle = "Storage & Media Access",
        permissionStorageDesc = "Required to save photos, audio notes, and videos in Media Hub.",
        permissionGrantedBadge = "Active",
        permissionMissingBadge = "Grant Access",
        permissionContinueBtn = "Continue to DSZ Save Chat"
    )

    private val urdu = LocalizedContent(
        appName = "ڈی ایس زیڈ سیو چیٹ",
        brandSlogan = "مقصد کے ساتھ تعمیر۔ لوگوں کے لیے تخلیق۔",
        authorTagline = "از ایم واصف ڈی ایس زیڈ",
        splashSubtitle = "آف لائن چیٹ سیور اور محفوظ شدہ پیغامات",
        splashLoading = "محفوظ آف لائن انجن شروع ہو رہا ہے...",
        tabChats = "چیٹس",
        tabMedia = "میڈیا",
        tabSettings = "سیٹنگز",
        subTabAll = "تمام",
        subTabMessenger = "میسنجر",
        subTabBusiness = "بزنس",
        searchChatsPlaceholder = "محفوظ شدہ چیٹس اور پیغامات تلاش کریں...",
        filterAll = "تمام پیغامات",
        filterDeleted = "ڈیلیٹ شدہ الرٹس",
        filterWhatsApp = "واٹس ایپ",
        filterTelegram = "ٹیلی گرام",
        filterDirect = "ڈائریکٹ",
        emptyChatsTitle = "کوئی چیٹ موجود نہیں",
        emptyChatsSubtitle = "موصول ہونے والے نوٹیفیکیشنز اور چیٹ بیک اپس یہاں آف لائن محفوظ ہوں گے۔",
        mediaEmptyTitle = "کوئی محفوظ شدہ میڈیا موجود نہیں",
        mediaEmptySubtitle = "نوٹیفیکیشنز سے محفوظ کی گئی ڈیلیٹ شدہ تصاویر اور ویڈیوز یہاں دکھائی دیں گی۔",
        adBannerTitle = "اشتہار • ڈی ایس زیڈ نیٹ ورک",
        deletedMessageBadge = "ڈیلیٹ شدہ بحال",
        secureOfflineBadge = "۱۰۰٪ آف لائن",
        addTestChatButton = "نیا فرضی پیغام شامل کریں",
        exportChatsButton = "آف لائن بیک اپ برآمد کریں",
        themeSectionTitle = "تھیم اور ظاہری شکل",
        themeSystem = "سسٹم ڈیفالٹ",
        themeLight = "لائٹ کریم تھیم",
        themeDark = "چارکول گولڈ ڈارک تھیم (ڈیفالٹ)",
        languageSectionTitle = "زبان کا انتخاب",
        youtubeSectionTitle = "تخلیق کار کا آفیشل چینل",
        youtubeChannelName = "واصف ریفری کول (Wasif RefriCool)",
        youtubeChannelHandle = "@WasifRefriCool",
        youtubeChannelDesc = "ایم واصف ڈی ایس زیڈ کا آفیشل چینل — ریفریجریشن، ایئر کنڈیشننگ اور ٹیکنالوجی کی مکمل رہنمائی اور ویڈیوز۔",
        youtubeSubscribeBtn = "چینل سبسکرائب کریں",
        youtubeWatchBtn = "ٹیوٹوریلز دیکھیں",
        youtubeSubscribersCount = "۱۵ ہزار+ سبسکرائبرز",
        youtubeVideosCount = "۱۸۰+ ویڈیوز",
        aboutDeveloperTitle = "ڈویلپر اور برانڈ کے بارے میں",
        developerName = "ایم واصف ڈی ایس زیڈ",
        developerRole = "سافٹ ویئر آرکیٹیکٹ و تخلیق کار",
        privacyTitle = "مکمل آف لائن گارنٹی",
        privacyDesc = "آپ کا تمام ڈیٹا صرف آپ کے موبائل میں محفوظ رہتا ہے۔ کوئی کلاؤڈ یا سرور استعمال نہیں ہوتا۔",
        replaySplashButton = "سپلیش اسکرین دیکھیں",
        offlineStatusTitle = "۱۰۰٪ آف لائن اور محفوظ",
        offlineStatusDesc = "کوئی بیرونی سرور یا ڈیٹا شیئرنگ نہیں۔ مکمل رازداری کے ساتھ محفوظ۔",
        settingLanguageTitle = "ایپ کی زبان",
        settingLanguageSubtitle = "ایپ کی زبان کو انگریزی اور اردو کے درمیان فوری تبدیل کریں۔",
        settingThemeTitle = "تھیم کی ظاہری شکل",
        settingThemeSubtitle = "ڈیفالٹ ڈارک موڈ اور لائٹ موڈ کے درمیان آسانی سے تبدیلی کریں۔",
        settingModeTitle = "آن لائن اور آف لائن موڈ",
        settingModeSubtitle = "پہلے سے آن لائن (آف) ہے۔ ۲۴ گھنٹے آف لائن سیونگ کے لیے آن کریں۔",
        settingPrimaryLockTitle = "پرائمری ایپ لاک",
        settingPrimaryLockSubtitle = "اصل چیٹ ہسٹری کے لیے ۴ ہندسوں کا پن سیٹ، تبدیل یا ختم کریں۔",
        settingVaultLockTitle = "والٹ / سیکنڈری لاک",
        settingVaultLockSubtitle = "خفیہ ڈیکوائے پن سیٹ، تبدیل یا ختم کریں جو خالی والٹ کھولے۔",
        settingAutoDownloadTitle = "میڈیا آٹو ڈاؤن لوڈ",
        settingAutoDownloadSubtitle = "ڈیلیٹ شدہ تصاویر اور ویڈیوز خودکار محفوظ کریں یا دستی ڈاؤن لوڈ کریں۔",
        settingStorageTitle = "سٹوریج اور میڈیا کلینر",
        settingStorageSubtitle = "ایپ کا سٹوریج استعمال دیکھیں اور کیش یا پرانی فائلیں محفوظ طریقے سے صاف کریں۔",
        settingBatteryTitle = "بیٹری آپٹیمائزیشن گائیڈ",
        settingBatterySubtitle = "یقینی بنائیں کہ ایپ بیک گراؤنڈ میں بغیر بند ہوئے ۲۴ گھنٹے آسانی سے چلے۔",
        settingUpdatesTitle = "تازہ ترین اپ ڈیٹس چیک کریں",
        settingUpdatesSubtitle = "ریموٹ ورژن چیک کریں اور نیا اے پی کے براؤزر میں ڈاؤن لوڈ کریں۔",
        updatesCurrentVersionTitle = "موجودہ ورژن: v2.4.0 (مستحکم ریلیز)",
        updatesCheckNowBtn = "اپ ڈیٹس تلاش کریں",
        updatesDownloadBtn = "ابھی اپ ڈیٹ کریں (Download APK)",
        updatesUpToDateDesc = "آپ ڈی ایس زیڈ سیو چیٹ کا آفیشل ورژن استعمال کر رہے ہیں۔ اپ ڈیٹ کے دوران ڈیٹا محفوظ رہے گا۔",
        updatesChangelogTitle = "حالیہ اپ ڈیٹس اور فیچرز",
        footerSlogan = "مقصد کے ساتھ تعمیر۔ لوگوں کے لیے تخلیق۔",
        settingPermissionsTitle = "نوٹیفکیشن اور ایپ پرمیشنز",
        settingPermissionsSubtitle = "واٹس ایپ انٹرسیپشن اور اسٹوریج پرمیشنز کا انتظام کریں۔",
        permissionNotificationTitle = "نوٹیفکیشن تک رسائی",
        permissionNotificationDesc = "واٹس ایپ پیغامات کو فوری انٹرسیپٹ کرنے کے لیے لازمی ہے۔",
        permissionStorageTitle = "اسٹوریج اور میڈیا تک رسائی",
        permissionStorageDesc = "میڈیا ہب میں تصاویر، آڈیو اور ویڈیوز محفوظ کرنے کے لیے لازمی ہے۔",
        permissionGrantedBadge = "فعال",
        permissionMissingBadge = "پرمیشن دیں",
        permissionContinueBtn = "ڈی ایس زیڈ سیو چیٹ کھولیں"
    )

    fun get(language: AppLanguage): LocalizedContent {
        return when (language) {
            AppLanguage.ENGLISH -> english
            AppLanguage.URDU -> urdu
        }
    }
}
